site_name: OneWelcome Identity Cloud for Developers
site_description: 'Documentation of the OneWelcome Identity Cloud: architecture, concepts, functional descriptions and the APIs explained.'
repo_url: https://github.com/onewelcome/onegini-identity-cloud-documentation

nav:
  - 'Introduction': index.md
  - 'OneWelcome Identity Cloud':
      - 'Platform architecture':
          - 'Mobile Identity & Access': architecture/mobile-identity-access.md
          - 'Identity & Single Sign-On': architecture/identity-single-sign-on.md
          - 'Interfaces': architecture/interfaces.md
  - 'Topic guides':
      - 'Third party identity providers': identity-providers.md
      - 'Single sign-on (SSO)':
          - 'Protected data in Single Page Apps': single-sign-on/protected-data-openid-connect-access-tokens.md
      - 'Client environment embedding (implementation)':
          - 'OAuth vs OpenID Connect': oauth-vs-oidc.md
          - 'Responsibilities of external system connected to DABP': dabp/guides/technical/external-systems-responsibilities.md
  - 'Products':
      - 'Customer Service': products/customer-service.md
      - 'Messaging service':
          - 'Introduction': messaging-service/index.md
          - 'Configuration':
              - 'SMS gateway configuration': messaging-service/sms-config.md
              - 'Email gateway configuration': messaging-service/email-config.md
          - 'API Reference': messaging-service/outgoing-api-spec.md
      - 'Delegated administration':
          - 'Introduction': dabp/index.md
          - 'Release notes': dabp/release-notes/index.md
          - 'Concepts':
              - 'In-depth view on permissions': dabp/guides/concepts/permissions-in-depth.md
              - 'In-depth view on policies': dabp/guides/concepts/policies-in-depth.md
              - 'In-depth view on resources': dabp/guides/concepts/resources-in-depth.md
          - 'How to - Functional':
              - 'Inviting users in DABP': dabp/guides/functional/inviting-users.md
              - 'Managing subgroups - Best practices': dabp/guides/functional/subgroups-best-practices.md
              - 'How and when to use custom attributes on groups': dabp/guides/functional/group-attributes.md
              - 'Manage policies': dabp/guides/functional/manage-policy-via-ui.md
              - 'Manage resources': dabp/guides/functional/manage-resource-via-ui.md
          - 'How to - Technical':
              - 'How to create a new policy via the API': dabp/guides/technical/create-policy-via-api.md
              - 'How to create a new resource type via the API': dabp/guides/technical/create-resource-type-via-api.md
              - 'How to create a new resource via the API': dabp/guides/technical/create-resource-via-api.md
              - 'Person report': dabp/guides/technical/person-report.md
              - 'Non-personal requests': dabp/guides/technical/non-personal-requests.md
              - 'Responsibilities of the external system connected to DABP': dabp/guides/technical/external-systems-responsibilities.md
              - 'Using Customer Self Styling for changing looks and behaviour of DABP': dabp/guides/technical/using-ers.md
              - 'Example palette.json': dabp/guides/technical/palette-example.md
      - 'Identity & Single Sign-On': products/identity-single-sign-on.md
      - 'Access': https://thalesdocs.com/oip/idaas-core/idaas-core-access/index.html
      - 'Mobile Identity': products/mobile-identity.md
      - Self-styling:
          - 'Introduction': self-styling/index.md
          - 'Frontend styling': self-styling/configuration-page.md
          - 'Release notes': self-styling/release-notes/release-notes.md
copyright: "OneWelcome B.V."

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/reading-time.js
  - javascripts/mermaid-config.js
  - javascripts/mermaid-custom-loader.js

theme:
  name: 'material'
  logo: 'images/onegini-logo-white.svg'
  favicon: 'images/favicon.ico'
  font: false
  custom_dir: 'theme'

extra:
  search:
    tokenizer: '[\s\-\.]+'
  manifest: 'manifest.webmanifest'
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OneWelcome
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/onewelcome/

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
